export const uiTypes = {
  SET_ERRORS: "SET_ERRORS",
  LOADING_UI: "LOADING_UI",
  CLEAR_ERRORS: "CLEAR_ERRORS",
  SERVER_ERROR: "SERVER_ERROR",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SET_ERROR: "SET_ERROR",
  SET_ERRORS_SIGNUP_SELLER: "SET_ERRORS_SIGNUP_SELLER",
  SET_ERROR_ITEM: "SET_ERROR_ITEM",
};
